services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: insecure_comm
      # It is recommended to also have an application user and not just root:
      MYSQL_USER: app
      MYSQL_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/db:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-pexample"]
      interval: 5s
      timeout: 3s
      retries: 20
    ports:
      - "3307:3306"

  backend:
    build: ./backend
    ports:
      - "8081:8080"
    depends_on:
      db:
        condition: service_healthy
      mailhog:
        condition: service_started
    # Loads environment variables from backend/.env
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/config/password-policy.toml:/app/config/password-policy.toml:ro  

  frontend:
    build: ./frontend
    ports:
      - "3001:80"
    depends_on:
      - backend

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1026:1025"  # SMTP
      - "8026:8025"  # Web UI    

volumes:
  db_data:
